"""civ6-mcp backend — drives Civ6 via the upstream civ6-mcp MCP server.

The upstream project (github.com/lmwilki/civ6-mcp) exposes Civ6's internal
state and commands through a Python MCP server that talks to the game over
FireTuner TCP. We treat it as a black box and wrap it as a backend, leaving
the existing VLM/computer-use stack untouched.
"""

from civStation.agent.modules.backend.civ6_mcp.action_mapping import (
    PLANNED_ACTION_TYPE_TO_MCP_TOOL,
    Civ6McpActionMappingError,
    MappedCiv6McpAction,
    map_civ6_mcp_action,
    map_civ6_mcp_action_details,
    map_civ6_mcp_actions,
)
from civStation.agent.modules.backend.civ6_mcp.client import (
    Civ6McpClient,
    Civ6McpClientProtocol,
    Civ6McpConfig,
    Civ6McpError,
    Civ6McpHealth,
    Civ6McpUnavailableError,
)
from civStation.agent.modules.backend.civ6_mcp.executor import (
    Civ6McpExecutor,
    coerce_tool_call,
    coerce_tool_calls,
)
from civStation.agent.modules.backend.civ6_mcp.observation_schema import (
    CIV6_MCP_CONTEXT_FIELD_MAPPINGS,
    CIV6_MCP_OBSERVATION_SECTION_MAPPINGS,
    Civ6McpContextFieldMapping,
    Civ6McpNormalizedObservation,
    Civ6McpObservationSectionMapping,
    build_game_observation_updates,
    build_global_context_updates,
    build_situation_summary,
    normalize_observation_bundle,
    normalize_raw_mcp_game_state,
    render_planner_context,
    section_texts_for_bundle,
)
from civStation.agent.modules.backend.civ6_mcp.observer import (
    DEFAULT_CIV6_MCP_OBSERVE_TOOLS,
    Civ6McpObserver,
    build_civ6_mcp_observer,
)
from civStation.agent.modules.backend.civ6_mcp.operations import (
    ACTION_TOOLS,
    END_TURN_REFLECTION_FIELDS,
    END_TURN_TOOL,
    OBSERVATION_TOOLS,
    SUPPORTED_CIV6_MCP_TOOLS,
    Civ6McpDispatchResult,
    Civ6McpOperationDispatcher,
    Civ6McpRequest,
    Civ6McpRequestBuilder,
    SupportedCiv6McpOperation,
    classify_civ6_mcp_text,
    coerce_civ6_mcp_requests,
    operation_for_tool,
    validate_civ6_mcp_request,
)
from civStation.agent.modules.backend.civ6_mcp.planner import Civ6McpToolPlanner, PlannerResult
from civStation.agent.modules.backend.civ6_mcp.planner_types import (
    Civ6McpAction,
    Civ6McpActionType,
    Civ6McpBackendAction,
    Civ6McpBackendIntent,
    Civ6McpIntent,
    Civ6McpIntentKind,
    Civ6McpIntentType,
    Civ6McpPlanner,
    Civ6McpPlannerAction,
    Civ6McpPlannerIntent,
    Civ6McpPlannerProvider,
    Civ6McpPlannerResponse,
    infer_civ6_mcp_intent_type,
)
from civStation.agent.modules.backend.civ6_mcp.response import (
    Civ6McpNormalizedResult,
    Civ6McpResponseClassification,
    normalize_mcp_response_error,
    normalize_mcp_response_text,
    normalize_mcp_response_timeout,
    normalize_mcp_tool_result,
)
from civStation.agent.modules.backend.civ6_mcp.results import (
    ToolCall,
    ToolCallResult,
    executor_result_from_mcp_error,
    executor_result_from_mcp_timeout,
    executor_result_from_mcp_tool_result,
    executor_result_from_normalized_response,
    tool_call_result_from_dispatch,
)
from civStation.agent.modules.backend.civ6_mcp.state_parser import (
    GameOverviewSnapshot,
    StateBundle,
    parse_game_overview,
    state_bundle_from_raw_mcp_state,
)
from civStation.agent.modules.backend.civ6_mcp.turn_loop import (
    Civ6McpClientFactory,
    Civ6McpObserverFactory,
    Civ6McpTurnConfig,
    Civ6McpTurnLoopConfig,
    Civ6McpTurnRequestContext,
    Civ6McpTurnResult,
    Civ6McpTurnState,
    build_civ6_mcp_client,
    run_civ6_mcp_turn_loop,
    run_multi_turn_civ6_mcp,
    run_one_turn_civ6_mcp,
)
from civStation.agent.modules.backend.civ6_mcp.turn_planning import (
    Civ6McpPrioritizedIntent,
    Civ6McpTurnPlan,
    build_prioritized_turn_plan,
)

__all__ = [
    "Civ6McpClient",
    "Civ6McpClientProtocol",
    "Civ6McpConfig",
    "Civ6McpError",
    "Civ6McpHealth",
    "Civ6McpClientFactory",
    "Civ6McpIntent",
    "Civ6McpIntentKind",
    "Civ6McpIntentType",
    "Civ6McpNormalizedResult",
    "Civ6McpNormalizedObservation",
    "Civ6McpObservationSectionMapping",
    "Civ6McpContextFieldMapping",
    "Civ6McpResponseClassification",
    "Civ6McpUnavailableError",
    "Civ6McpAction",
    "Civ6McpActionMappingError",
    "Civ6McpActionType",
    "Civ6McpBackendAction",
    "Civ6McpBackendIntent",
    "Civ6McpExecutor",
    "Civ6McpObserver",
    "Civ6McpOperationDispatcher",
    "Civ6McpObserverFactory",
    "Civ6McpPlanner",
    "Civ6McpPlannerAction",
    "Civ6McpPlannerIntent",
    "Civ6McpPlannerProvider",
    "Civ6McpPlannerResponse",
    "Civ6McpPrioritizedIntent",
    "Civ6McpRequest",
    "Civ6McpRequestBuilder",
    "Civ6McpDispatchResult",
    "Civ6McpToolPlanner",
    "Civ6McpTurnPlan",
    "Civ6McpTurnConfig",
    "Civ6McpTurnLoopConfig",
    "Civ6McpTurnRequestContext",
    "Civ6McpTurnResult",
    "Civ6McpTurnState",
    "GameOverviewSnapshot",
    "MappedCiv6McpAction",
    "PlannerResult",
    "PLANNED_ACTION_TYPE_TO_MCP_TOOL",
    "StateBundle",
    "SupportedCiv6McpOperation",
    "ToolCall",
    "ToolCallResult",
    "ACTION_TOOLS",
    "CIV6_MCP_CONTEXT_FIELD_MAPPINGS",
    "CIV6_MCP_OBSERVATION_SECTION_MAPPINGS",
    "DEFAULT_CIV6_MCP_OBSERVE_TOOLS",
    "END_TURN_REFLECTION_FIELDS",
    "END_TURN_TOOL",
    "OBSERVATION_TOOLS",
    "SUPPORTED_CIV6_MCP_TOOLS",
    "build_civ6_mcp_client",
    "build_civ6_mcp_observer",
    "build_game_observation_updates",
    "build_global_context_updates",
    "build_situation_summary",
    "build_prioritized_turn_plan",
    "classify_civ6_mcp_text",
    "coerce_civ6_mcp_requests",
    "coerce_tool_call",
    "coerce_tool_calls",
    "executor_result_from_mcp_error",
    "executor_result_from_mcp_timeout",
    "executor_result_from_mcp_tool_result",
    "executor_result_from_normalized_response",
    "infer_civ6_mcp_intent_type",
    "map_civ6_mcp_action",
    "map_civ6_mcp_action_details",
    "map_civ6_mcp_actions",
    "normalize_mcp_response_error",
    "normalize_mcp_response_text",
    "normalize_mcp_response_timeout",
    "normalize_mcp_tool_result",
    "operation_for_tool",
    "parse_game_overview",
    "normalize_observation_bundle",
    "normalize_raw_mcp_game_state",
    "render_planner_context",
    "run_civ6_mcp_turn_loop",
    "run_multi_turn_civ6_mcp",
    "run_one_turn_civ6_mcp",
    "section_texts_for_bundle",
    "state_bundle_from_raw_mcp_state",
    "tool_call_result_from_dispatch",
    "validate_civ6_mcp_request",
]
