"""
Strategy Schemas - Data structures for strategic planning.

Defines the StructuredStrategy dataclass and related enums
for representing game strategies in a structured format.
"""

import json
import logging
from dataclasses import dataclass, field
from enum import Enum

logger = logging.getLogger(__name__)


class VictoryType(str, Enum):
    """Types of victory conditions in Civilization VI."""

    SCIENCE = "science"
    CULTURE = "culture"
    DOMINATION = "domination"
    RELIGIOUS = "religious"
    DIPLOMATIC = "diplomatic"
    SCORE = "score"


class GamePhase(str, Enum):
    """General phases of a Civilization game."""

    EARLY_EXPANSION = "early_expansion"  # Turns 1-50: Settling, exploring
    MID_DEVELOPMENT = "mid_development"  # Turns 50-150: Building infrastructure
    LATE_CONSOLIDATION = "late_consolidation"  # Turns 150-250: Pushing toward victory
    VICTORY_PUSH = "victory_push"  # Turns 250+: Final push for victory


@dataclass
class StructuredStrategy:
    """
    Structured representation of a game strategy.

    This is the output of the Strategy Planner and is used to guide
    primitive-level decision making throughout the game.

    - text: LLM이 작성한 전략 본문 (한국어, free-form). 프롬프트에 직접 주입됨.
    - primitive_directives: 각 primitive별 구체적 행동 기준.
      Primitive-specific action guidelines generated by the strategy planner.
      e.g. {"unit_ops": "개척자: 산 인접 정착", "city_production": "캠퍼스 > 도서관"}
    - victory_goal / current_phase: 프로그래밍 접근용 메타데이터.
    """

    text: str = ""
    victory_goal: VictoryType = VictoryType.SCIENCE
    current_phase: str = "early_expansion"
    primitive_hint: str = ""  # micro-level behavioral directive from HITL
    primitive_directives: dict[str, str] = field(default_factory=dict)

    def to_prompt_string(self) -> str:
        """
        Convert strategy to a string suitable for LLM prompts.

        Combines the main strategy text with primitive-specific directives.
        """
        parts = [self.text]
        if self.primitive_directives:
            lines = ["\n[프리미티브별 행동 기준]"]
            for prim, directive in self.primitive_directives.items():
                lines.append(f"- {prim}: {directive}")
            parts.append("\n".join(lines))
        return "\n".join(parts)

    @classmethod
    def default_science_strategy(cls) -> "StructuredStrategy":
        """Create a default science victory strategy."""
        return cls(
            text=(
                "[과학 승리 전략]\n"
                "캠퍼스 건설을 최우선으로 하고, 도서관→대학→연구소 순으로 과학 인프라를 확보한다. "
                "초반에는 도시 2-3개를 빠르게 정착하고 인구 성장에 집중한다.\n"
                "우선순위: 캠퍼스 건설 > 핵심 기술 연구 > 도시 성장 > 방어력 유지\n"
                "제약사항: 불필요한 전쟁 회피, 군사비 과다 지출 지양\n"
                "즉각적 목표: 도서관 건설, 필기 연구, 제2도시 정착\n"
                "장기 목표: 캠퍼스 3개 이상, 현대 시대 도달, 우주선 발사"
            ),
            victory_goal=VictoryType.SCIENCE,
            current_phase="early_expansion",
            primitive_directives={
                "유닛 조작": "개척자: 산 인접(캠퍼스 보너스) 위치에서 정착. 건설자: 자원 개선 우선.",
                "도시 생산": "캠퍼스 > 도서관 > 대학 순서 우선. 방어 위협 시 성벽/유닛.",
                "기술 연구": "필기 → 교육 → 과학혁명 경로. 유레카 달성 기술 우선.",
                "사회 제도": "문화 출력 높이는 제도 우선. 영감 달성 제도 효율적으로.",
                "총독": "핑갈라(교육자) 임명 우선. 수도 또는 인구 최대 도시에 배치.",
                "외교": "평화·우호 관계 유지. 불필요한 전쟁 회피.",
                "전투": "자국 영토 내 적 반드시 제거. 야만인 적극 토벌. 불필요한 원정 회피.",
                "정책": "과학 산출 증가 카드 우선 장착. 자연철학, 합리주의 등.",
            },
        )

    @classmethod
    def default_culture_strategy(cls) -> "StructuredStrategy":
        """Create a default culture victory strategy."""
        return cls(
            text=(
                "[문화 승리 전략]\n"
                "극장가 건설을 최우선으로 하고, 위인 확보와 유산 건설을 통해 관광을 극대화한다. "
                "초반에는 문화 출력을 높여 정책 카드를 빠르게 확보하고, 걸작을 수집한다.\n"
                "우선순위: 극장가 건설 > 위인 확보 > 유산 건설 > 관광 강화\n"
                "제약사항: 유산 경쟁 패배 시 대안 마련, 외교적 고립 방지\n"
                "즉각적 목표: 원형극장 건설, 걸작 확보, 축제 개최\n"
                "장기 목표: 5개 극장가 건설, 록밴드 활용, 해외 관광객 유치"
            ),
            victory_goal=VictoryType.CULTURE,
            current_phase="early_expansion",
            primitive_directives={
                "유닛 조작": "개척자: 자연경관·해안 근처에서 정착. 건설자: 자원 개선 우선.",
                "도시 생산": "극장가 > 원형극장 > 유산 우선. 위인 포인트 확보.",
                "기술 연구": "문화 관련 기술 우선. 인쇄술, 라디오 등 관광 보너스 기술.",
                "사회 제도": "연극/문학 → 인문주의 경로. 영감 달성 제도 우선.",
                "총독": "핑갈라(교육자) 문화 스킬 트리 우선. 수도 배치.",
                "외교": "우호 관계·개방 국경으로 관광 유입 극대화. 전쟁 회피.",
                "전투": "방어 위주. 자국 영토 방어만 수행. 불필요한 원정 절대 금지.",
                "정책": "문화·관광 산출 증가 카드 우선. 위인 포인트 증가 카드.",
            },
        )

    @classmethod
    def default_domination_strategy(cls) -> "StructuredStrategy":
        """Create a default domination victory strategy."""
        return cls(
            text=(
                "[지배 승리 전략]\n"
                "군사 유닛 생산과 병영 건설을 최우선으로 하고, 전략 자원을 조기에 확보한다. "
                "초반에는 정찰로 적 위치를 파악하고, 궁수 업그레이드 후 공세를 시작한다.\n"
                "우선순위: 군사 유닛 생산 > 병영 건설 > 전략 자원 확보 > 적 수도 점령\n"
                "제약사항: 다수 문명과 동시 전쟁 회피, 보급선 유지\n"
                "즉각적 목표: 전사 2기 생산, 궁수 업그레이드, 정찰 수행\n"
                "장기 목표: 모든 수도 점령, 군사 기술 우위 유지, 동맹 활용"
            ),
            victory_goal=VictoryType.DOMINATION,
            current_phase="early_expansion",
            primitive_directives={
                "유닛 조작": "개척자: 전선 방향·전략 자원 근처 정착. 전투 유닛: 적극 공격, 적 영토 전진.",
                "도시 생산": "병영 > 군사 유닛 > 성벽 우선. 공성 유닛 조기 확보.",
                "기술 연구": "청동기 → 철기 → 군사 기술 경로. 공성 기술 우선.",
                "사회 제도": "군사전통 → 봉건제도 경로. 군사 정책 슬롯 확보.",
                "총독": "빅토르(성주) 전선 도시에 배치. 군사 방어 스킬 우선.",
                "외교": "전쟁 선포에 유리하면 수락. 방어 동맹 활용. 다수 적 동시 교전 회피.",
                "전투": "적극 공격. 적 도시 체력 낮으면 점령 최우선. 수적 불리해도 전략적 가치 있으면 공격.",
                "정책": "군사 산출·경험치 증가 카드 우선. 규율, 전략 등.",
            },
        )


class HITLInputRequiredError(Exception):
    """Raised when HITL mode is enabled but no human input was provided."""

    pass


def parse_strategy_json(raw_json: str) -> StructuredStrategy:
    """
    Parse a JSON string into a StructuredStrategy.

    Expected format:
        {"victory_goal": "science", "current_phase": "early_expansion", "text": "..."}

    Raises:
        json.JSONDecodeError: If raw_json is not valid JSON
        ValueError: If the parsed text is too short (< 20 chars)
    """
    data = json.loads(raw_json)

    # Parse victory_goal with fallback
    victory_goal_str = data.get("victory_goal", "science").lower()
    try:
        victory_goal = VictoryType(victory_goal_str)
    except ValueError:
        logger.warning(f"Unknown victory type: {victory_goal_str}, defaulting to science")
        victory_goal = VictoryType.SCIENCE

    text = data.get("text", "")
    if len(text) < 20:
        raise ValueError(f"Strategy text too short ({len(text)} chars, minimum 20)")

    # Parse primitive_directives (optional dict)
    raw_directives = data.get("primitive_directives", {})
    if not isinstance(raw_directives, dict):
        raw_directives = {}
    primitive_directives = {k: v for k, v in raw_directives.items() if isinstance(k, str) and isinstance(v, str)}

    return StructuredStrategy(
        text=text,
        victory_goal=victory_goal,
        current_phase=data.get("current_phase", "early_expansion"),
        primitive_hint=data.get("primitive_hint", ""),
        primitive_directives=primitive_directives,
    )
