"""
Central Context Management Module.

Provides a unified context manager that maintains:
- GlobalContext: Map status, game statistics, diplomatic relations
- HighLevelContext: Strategy generated by the Strategy module
- PrimitiveContext: Short-term execution states and local data
"""

from civStation.agent.modules.context.context_manager import ContextManager
from civStation.agent.modules.context.context_updater import ContextUpdater
from civStation.agent.modules.context.global_context import GlobalContext
from civStation.agent.modules.context.high_level_context import HighLevelContext
from civStation.agent.modules.context.macro_turn_manager import MacroTurnManager, MacroTurnSummary
from civStation.agent.modules.context.primitive_context import PrimitiveContext
from civStation.agent.modules.context.turn_detector import TurnDetector

__all__ = [
    "ContextManager",
    "ContextUpdater",
    "GlobalContext",
    "HighLevelContext",
    "MacroTurnManager",
    "MacroTurnSummary",
    "PrimitiveContext",
    "TurnDetector",
]
