"""
Schema definitions for Civ6 AI Agent Actions and Plans.

This module defines the core data models for PyAutoGUI-based actions
with properly discriminated unions for type-safe serialization.
"""

from enum import Enum
from typing import Annotated, List, Literal, Optional, Union

from pydantic import BaseModel, Field


# Action type discriminator values
class ActionType(str, Enum):
    """Enum for action types corresponding to PyAutoGUI operations."""

    CLICK = "click"
    DOUBLE_CLICK = "double_click"
    PRESS = "press"
    DRAG = "drag"
    WAIT = "wait"


# Base Action model
class BaseAction(BaseModel):
    """Base class for all action types."""

    description: Optional[str] = Field(None, description="Optional description for debugging and logging")


# Concrete Action implementations with discriminator
class ClickAction(BaseAction):
    """Single click action at specified coordinates."""

    type: Literal[ActionType.CLICK] = ActionType.CLICK
    x: int = Field(..., description="X coordinate for click")
    y: int = Field(..., description="Y coordinate for click")
    button: str = Field("left", description="Mouse button: 'left', 'right', or 'middle'")


class DoubleClickAction(BaseAction):
    """Double click action at specified coordinates."""

    type: Literal[ActionType.DOUBLE_CLICK] = ActionType.DOUBLE_CLICK
    x: int = Field(..., description="X coordinate for double click")
    y: int = Field(..., description="Y coordinate for double click")
    button: str = Field("left", description="Mouse button: 'left', 'right', or 'middle'")


class KeyPressAction(BaseAction):
    """Keyboard key press action."""

    type: Literal[ActionType.PRESS] = ActionType.PRESS
    keys: List[str] = Field(..., description="List of keys to press (e.g., ['ctrl', 'c'])")
    interval: float = Field(0.1, description="Interval between key presses in seconds")


class DragAction(BaseAction):
    """Mouse drag action from start to end coordinates."""

    type: Literal[ActionType.DRAG] = ActionType.DRAG
    start_x: int = Field(..., description="Starting X coordinate")
    start_y: int = Field(..., description="Starting Y coordinate")
    end_x: int = Field(..., description="Ending X coordinate")
    end_y: int = Field(..., description="Ending Y coordinate")
    duration: float = Field(0.5, description="Duration of drag in seconds")
    button: str = Field("left", description="Mouse button to use for dragging")


class WaitAction(BaseAction):
    """Wait/sleep action."""

    type: Literal[ActionType.WAIT] = ActionType.WAIT
    duration: float = Field(..., description="Duration to wait in seconds")


# Discriminated union of all action types
Action = Annotated[
    Union[ClickAction, DoubleClickAction, KeyPressAction, DragAction, WaitAction],
    Field(discriminator="type"),
]


# Agent Plan model
class AgentPlan(BaseModel):
    """
    Complete action plan generated by a primitive.

    Contains the primitive name, reasoning, and sequence of actions to execute.
    """

    primitive_name: str = Field(..., description="Name of the primitive that generated this plan")
    reasoning: str = Field(..., description="Explanation of why these actions were chosen")
    actions: List[Action] = Field(default_factory=list, description="Ordered list of actions to execute")
