"""
Central Context Management Module.

Provides a unified context manager that maintains:
- GlobalContext: Map status, game statistics, diplomatic relations
- HighLevelContext: Strategy generated by the Strategy module
- PrimitiveContext: Short-term execution states and local data
"""

from computer_use_test.agent.modules.context.context_manager import ContextManager
from computer_use_test.agent.modules.context.context_updater import ContextUpdater
from computer_use_test.agent.modules.context.global_context import GlobalContext
from computer_use_test.agent.modules.context.high_level_context import HighLevelContext
from computer_use_test.agent.modules.context.macro_turn_manager import MacroTurnManager, MacroTurnSummary
from computer_use_test.agent.modules.context.primitive_context import PrimitiveContext

__all__ = [
    "ContextManager",
    "ContextUpdater",
    "GlobalContext",
    "HighLevelContext",
    "MacroTurnManager",
    "MacroTurnSummary",
    "PrimitiveContext",
]
