"""
Context Manager - Central singleton for all game state contexts.

Provides a unified interface to access and update all context types:
- GlobalContext: Map status, game statistics, diplomatic relations
- HighLevelContext: Strategy generated by the Strategy module
- PrimitiveContext: Short-term execution states and local data
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from threading import Lock
from typing import TYPE_CHECKING, Any

from computer_use_test.agent.modules.context.global_context import GlobalContext
from computer_use_test.agent.modules.context.high_level_context import HighLevelContext
from computer_use_test.agent.modules.context.primitive_context import PrimitiveContext

if TYPE_CHECKING:
    from computer_use_test.agent.modules.strategy.strategy_schemas import StructuredStrategy

logger = logging.getLogger(__name__)


@dataclass
class TurnRecord:
    """Record of a single turn's execution."""

    turn_number: int
    primitive_used: str
    actions_taken: int
    success: bool
    timestamp: datetime = field(default_factory=datetime.now)
    notes: str = ""


class ContextManager:
    """
    Singleton central state manager for all game contexts.

    This class provides a unified interface to access and update
    GlobalContext, HighLevelContext, and PrimitiveContext.

    Usage:
        ctx = ContextManager.get_instance()
        ctx.update_global_context(current_turn=150)
        ctx.set_strategy(strategy)
        context_string = ctx.get_combined_context()
    """

    _instance: ContextManager | None = None
    _lock: Lock = Lock()

    def __new__(cls) -> ContextManager:
        """Ensure singleton instance."""
        if cls._instance is None:
            with cls._lock:
                # Double-check locking pattern
                if cls._instance is None:
                    instance = super().__new__(cls)
                    instance._initialized = False
                    cls._instance = instance
        return cls._instance

    def __init__(self) -> None:
        """Initialize contexts (only once due to singleton)."""
        if getattr(self, "_initialized", False):
            return

        # Sub-contexts
        self.global_context: GlobalContext = GlobalContext()
        self.high_level_context: HighLevelContext = HighLevelContext()
        self.primitive_context: PrimitiveContext = PrimitiveContext()

        # History tracking
        self._turn_history: list[TurnRecord] = []
        self._action_count_this_turn: int = 0

        # Metadata
        self._session_start: datetime = datetime.now()
        self._last_update: datetime = datetime.now()

        self._initialized = True
        logger.info("ContextManager initialized")

    @classmethod
    def get_instance(cls) -> ContextManager:
        """Get the singleton instance of ContextManager."""
        return cls()

    @classmethod
    def reset_instance(cls) -> None:
        """Reset the singleton instance (useful for testing)."""
        with cls._lock:
            cls._instance = None

    # ==================== Read Methods ====================

    def get_combined_context(self) -> str:
        """
        Get a combined context string from all sub-contexts.

        Returns a comprehensive summary suitable for LLM prompts.
        """
        sections = []

        # Global context
        global_str = self.global_context.to_prompt_string()
        if global_str:
            sections.append(global_str)

        # High-level context
        highlevel_str = self.high_level_context.to_prompt_string()
        if highlevel_str:
            sections.append(highlevel_str)

        # Primitive context (abbreviated)
        primitive_str = self.primitive_context.to_prompt_string()
        if primitive_str:
            sections.append(primitive_str)

        return "\n\n".join(sections) if sections else "게임 상태 정보 없음"

    def get_context_for_primitive(self, primitive_name: str) -> str:
        """
        Get context string tailored for a specific primitive.

        Different primitives may need different context emphasis.

        Args:
            primitive_name: Name of the primitive requesting context

        Returns:
            Context string optimized for the primitive
        """
        lines = []

        # Always include turn info
        lines.append(f"턴: {self.global_context.current_turn} ({self.global_context.game_era} 시대)")

        # Strategy summary
        strategy_str = self.high_level_context.get_strategy_string()
        lines.append(f"전략: {strategy_str}")

        # Primitive-specific context
        if primitive_name == "unit_ops_primitive":
            # Unit operations need military and unit info
            if self.global_context.units_by_type:
                lines.append(f"보유 유닛: {self.global_context.units_by_type}")
            if self.global_context.is_at_war():
                lines.append(f"⚔️ 전쟁 중: {', '.join(self.global_context.active_wars)}")
            if self.primitive_context.selected_unit_info:
                lines.append(f"선택된 유닛: {self.primitive_context.selected_unit_info}")

        elif primitive_name in ("research_select_primitive", "science_decision_primitive"):
            # Research needs science output and available techs
            lines.append(f"과학 출력: +{self.global_context.science_per_turn:.1f}/턴")
            if self.global_context.current_research:
                lines.append(
                    f"연구 중: {self.global_context.current_research} ({self.global_context.research_turns_left}턴)"
                )
            if self.global_context.available_techs:
                lines.append(f"연구 가능: {', '.join(self.global_context.available_techs[:5])}")

        elif primitive_name in ("culture_decision_primitive",):
            # Culture needs culture output and civics
            lines.append(f"문화 출력: +{self.global_context.culture_per_turn:.1f}/턴")
            if self.global_context.current_civic:
                lines.append(
                    f"사회제도: {self.global_context.current_civic} ({self.global_context.civic_turns_left}턴)"
                )
            if self.global_context.available_civics:
                lines.append(f"선택 가능: {', '.join(self.global_context.available_civics[:5])}")

        elif primitive_name == "city_production_primitive":
            # Production needs city info
            if self.global_context.cities:
                lines.append(f"도시 수: {len(self.global_context.cities)}")
                for city in self.global_context.cities[:3]:
                    if city.current_production:
                        lines.append(f"  {city.name}: {city.current_production} ({city.production_turns_left}턴)")

        elif primitive_name == "diplomatic_primitive":
            # Diplomacy needs civ relations
            if self.global_context.known_civilizations:
                lines.append("알려진 문명:")
                for civ in self.global_context.known_civilizations[:5]:
                    lines.append(f"  - {civ.name}: {civ.diplomatic_status.value}")

        elif primitive_name == "governor_primitive":
            # Governor needs city and governor info
            if self.global_context.cities:
                governed = [c for c in self.global_context.cities if c.has_governor]
                ungoverned = [c for c in self.global_context.cities if not c.has_governor]
                if governed:
                    lines.append(f"총독 배치된 도시: {', '.join(c.name for c in governed)}")
                if ungoverned:
                    lines.append(f"총독 미배치 도시: {', '.join(c.name for c in ungoverned)}")

        elif primitive_name == "policy_primitive":
            # Policy decisions - add any relevant policy context
            pass  # Currently no specific policy context in GlobalContext

        elif primitive_name == "combat_primitive":
            # Combat needs military strength and war status
            lines.append(f"군사력: {self.global_context.military_strength}")
            if self.global_context.is_at_war():
                lines.append(f"⚔️ 전쟁 상대: {', '.join(self.global_context.active_wars)}")

        # Add threats and opportunities if relevant
        if self.high_level_context.active_threats:
            lines.append(f"⚠️ 위협: {', '.join(self.high_level_context.active_threats[:3])}")

        # Add recent action context (avoid repeating same actions)
        if self.primitive_context.recent_actions:
            last_actions = self.primitive_context.get_last_actions(3)
            if last_actions:
                action_strs = []
                for a in last_actions:
                    if a.action_type == "click":
                        action_strs.append(f"click({a.x},{a.y})")
                    elif a.action_type == "press":
                        action_strs.append(f"press({a.key})")
                lines.append(f"최근 액션: {', '.join(action_strs)}")

        return "\n".join(lines) if lines else "게임 상태 정보 없음"

    def get_strategy_string(self) -> str:
        """Get the current strategy as a prompt string."""
        return self.high_level_context.get_strategy_string()

    # ==================== Write Methods ====================

    def update_global_context(self, **kwargs: Any) -> None:
        """
        Update global context fields.

        Args:
            **kwargs: Fields to update on GlobalContext
        """
        for key, value in kwargs.items():
            if hasattr(self.global_context, key):
                setattr(self.global_context, key, value)
            else:
                logger.warning(f"Unknown GlobalContext field: {key}")

        self.global_context.update_timestamp()
        self._last_update = datetime.now()

    def set_strategy(self, strategy: StructuredStrategy) -> None:
        """Set the current strategy."""
        self.high_level_context.set_strategy(strategy)
        self._last_update = datetime.now()
        logger.info(f"Strategy set: {strategy.victory_goal.value} victory, phase: {strategy.current_phase}")

    def record_action(
        self,
        action_type: str,
        primitive: str,
        x: int = 0,
        y: int = 0,
        end_x: int = 0,
        end_y: int = 0,
        key: str = "",
        text: str = "",
        result: str = "success",
        error_message: str = "",
    ) -> None:
        """
        Record an executed action.

        Args:
            action_type: Type of action (click, press, drag, etc.)
            primitive: Name of the primitive that generated the action
            x, y: Normalized coordinates (if applicable)
            end_x, end_y: End coordinates for drag actions
            key: Key pressed (for press actions)
            text: Text typed (for type actions)
            result: "success" or "failed"
            error_message: Error message if failed
        """
        self.primitive_context.add_action(
            action_type=action_type,
            primitive=primitive,
            x=x,
            y=y,
            end_x=end_x,
            end_y=end_y,
            key=key,
            text=text,
            result=result,
            error_message=error_message,
        )
        self._action_count_this_turn += 1
        self._last_update = datetime.now()

    def set_current_primitive(self, primitive_name: str) -> None:
        """Set the current primitive being executed."""
        self.primitive_context.set_current_primitive(primitive_name)

    def update_selected_unit(self, unit_info: dict[str, Any]) -> None:
        """Update the currently selected unit information."""
        self.primitive_context.update_selected_unit(unit_info)

    def advance_turn(self, primitive_used: str = "", success: bool = True, notes: str = "") -> None:
        """
        Record turn completion and advance to next turn.

        Args:
            primitive_used: Primary primitive used this turn
            success: Whether the turn was successful
            notes: Any notes about the turn
        """
        # Record turn history
        turn_record = TurnRecord(
            turn_number=self.global_context.current_turn,
            primitive_used=primitive_used,
            actions_taken=self._action_count_this_turn,
            success=success,
            notes=notes,
        )
        self._turn_history.append(turn_record)

        # Advance turn counter
        self.global_context.current_turn += 1
        self.global_context.update_timestamp()

        # Reset turn-specific state
        self._action_count_this_turn = 0
        self.primitive_context.reset()

        self._last_update = datetime.now()
        logger.info(f"Advanced to turn {self.global_context.current_turn}")

    def add_threat(self, threat: str) -> None:
        """Add an active threat."""
        self.high_level_context.add_threat(threat)

    def remove_threat(self, threat: str) -> None:
        """Remove a threat."""
        self.high_level_context.remove_threat(threat)

    def add_opportunity(self, opportunity: str) -> None:
        """Add an opportunity."""
        self.high_level_context.add_opportunity(opportunity)

    def remove_opportunity(self, opportunity: str) -> None:
        """Remove an opportunity."""
        self.high_level_context.remove_opportunity(opportunity)

    # ==================== Utility Methods ====================

    def get_turn_history(self, last_n: int | None = None) -> list[TurnRecord]:
        """Get turn history, optionally limited to last N turns."""
        if last_n is None:
            return self._turn_history
        return self._turn_history[-last_n:]

    def get_session_duration(self) -> float:
        """Get session duration in seconds."""
        return (datetime.now() - self._session_start).total_seconds()

    def to_dict(self) -> dict[str, Any]:
        """Convert all contexts to a dictionary for serialization."""
        return {
            "global": self.global_context.to_dict(),
            "high_level": self.high_level_context.to_dict(),
            "primitive": self.primitive_context.to_dict(),
            "session_start": self._session_start.isoformat(),
            "last_update": self._last_update.isoformat(),
            "turn_history_count": len(self._turn_history),
        }

    def __repr__(self) -> str:
        return (
            f"ContextManager(turn={self.global_context.current_turn}, "
            f"era={self.global_context.game_era}, "
            f"strategy={self.high_level_context.current_strategy is not None})"
        )
