"""
Context Manager - Central singleton for all game state contexts.

Provides a unified interface to access and update all context types:
- GlobalContext: Map status, game statistics, diplomatic relations
- HighLevelContext: Strategy generated by the Strategy module
- PrimitiveContext: Short-term execution states and local data
"""

# TODO: MCP 서버 연동 시, ContextManager에 MCP 데이터 소스를 추가 등록하여
#       VLM 비전 분석 결과와 게임 네이티브 데이터를 통합 관리할 것.
#       예) ctx.register_data_source("mcp", mcp_client) → update_global_context() 확장
# TODO: Context Length 관리 — get_context_for_primitive(), get_combined_context() 등이
#       반환하는 텍스트 길이가 VLM 토큰 한도를 초과하지 않도록 truncation/summarization 로직 추가.
#       특히 notes, recent_actions, macro_turn_summaries 등 누적 데이터의 최대 길이를 제한할 것.

from __future__ import annotations

import copy
import logging
from dataclasses import dataclass, field
from datetime import datetime
from threading import Lock
from typing import TYPE_CHECKING, Any

from computer_use_test.agent.modules.context.global_context import GlobalContext
from computer_use_test.agent.modules.context.high_level_context import HighLevelContext
from computer_use_test.agent.modules.context.primitive_context import PrimitiveContext

if TYPE_CHECKING:
    from computer_use_test.agent.modules.strategy.strategy_schemas import StructuredStrategy

logger = logging.getLogger(__name__)


@dataclass
class TurnRecord:
    """Record of a single turn's execution."""

    turn_number: int
    primitive_used: str
    actions_taken: int
    success: bool
    timestamp: datetime = field(default_factory=datetime.now)
    notes: str = ""


@dataclass
class PolicyTabCalibrationEntry:
    """One session-persistent policy tab coordinate."""

    tab_name: str
    screen_x: int
    screen_y: int
    confirmed: bool = False
    provisional: bool = False


@dataclass
class PolicyCaptureGeometry:
    """Game-window geometry used when the policy tab cache was recorded."""

    region_w: int
    region_h: int
    x_offset: int
    y_offset: int

    def to_dict(self) -> dict[str, int]:
        return {
            "region_w": self.region_w,
            "region_h": self.region_h,
            "x_offset": self.x_offset,
            "y_offset": self.y_offset,
        }


@dataclass
class PolicyTabCalibrationCache:
    """Session-wide calibrated policy tab cache."""

    positions: dict[str, PolicyTabCalibrationEntry] = field(default_factory=dict)
    confirmed_tabs: set[str] = field(default_factory=set)
    provisional_tabs: set[str] = field(default_factory=set)
    capture_geometry: PolicyCaptureGeometry | None = None
    calibration_complete: bool = False
    distinct_failures: set[str] = field(default_factory=set)

    def is_full(self) -> bool:
        required = {"군사", "경제", "외교", "와일드카드", "암흑"}
        return (
            set(self.positions) == required
            and self.confirmed_tabs == required
            and not self.provisional_tabs
            and self.calibration_complete
        )

    def to_dict(self) -> dict[str, object]:
        return {
            "positions": {
                tab_name: {
                    "tab_name": entry.tab_name,
                    "screen_x": entry.screen_x,
                    "screen_y": entry.screen_y,
                    "confirmed": entry.confirmed,
                    "provisional": entry.provisional,
                }
                for tab_name, entry in self.positions.items()
            },
            "confirmed_tabs": sorted(self.confirmed_tabs),
            "provisional_tabs": sorted(self.provisional_tabs),
            "capture_geometry": self.capture_geometry.to_dict() if self.capture_geometry is not None else None,
            "calibration_complete": self.calibration_complete,
            "distinct_failures": sorted(self.distinct_failures),
        }


class ContextManager:
    """
    Singleton central state manager for all game contexts.

    This class provides a unified interface to access and update
    GlobalContext, HighLevelContext, and PrimitiveContext.

    Usage:
        ctx = ContextManager.get_instance()
        ctx.update_global_context(current_turn=150)
        ctx.set_strategy(strategy)
        context_string = ctx.get_combined_context()
    """

    _instance: ContextManager | None = None
    _lock: Lock = Lock()

    def __new__(cls) -> ContextManager:
        """Ensure singleton instance."""
        if cls._instance is None:
            with cls._lock:
                # Double-check locking pattern
                if cls._instance is None:
                    instance = super().__new__(cls)
                    instance._initialized = False
                    cls._instance = instance
        return cls._instance

    def __init__(self) -> None:
        """Initialize contexts (only once due to singleton)."""
        if getattr(self, "_initialized", False):
            return

        # Sub-contexts
        self.global_context: GlobalContext = GlobalContext()
        self.high_level_context: HighLevelContext = HighLevelContext()
        self.primitive_context: PrimitiveContext = PrimitiveContext()

        # History tracking
        self._turn_history: list[TurnRecord] = []
        self._action_count_this_turn: int = 0

        # Macro-turn summaries (LLM-generated summaries of completed game turns)
        self._macro_turn_summaries: list[str] = []

        # Session-persistent policy tab calibration cache
        self._policy_tab_cache: PolicyTabCalibrationCache = PolicyTabCalibrationCache()

        # Metadata
        self._session_start: datetime = datetime.now()
        self._last_update: datetime = datetime.now()

        self._initialized = True
        logger.info("ContextManager initialized")

    @classmethod
    def get_instance(cls) -> ContextManager:
        """Get the singleton instance of ContextManager."""
        return cls()

    @classmethod
    def reset_instance(cls) -> None:
        """Reset the singleton instance (useful for testing)."""
        with cls._lock:
            cls._instance = None

    # ==================== Read Methods ====================

    def get_combined_context(self) -> str:
        """
        Get a combined context string from all sub-contexts.

        Returns a comprehensive summary suitable for LLM prompts.
        """
        sections = []

        # Global context
        global_str = self.global_context.to_prompt_string()
        if global_str:
            sections.append(global_str)

        # High-level context
        highlevel_str = self.high_level_context.to_prompt_string()
        if highlevel_str:
            sections.append(highlevel_str)

        # Primitive context (abbreviated)
        primitive_str = self.primitive_context.to_prompt_string()
        if primitive_str:
            sections.append(primitive_str)

        return "\n\n".join(sections) if sections else "게임 상태 정보 없음"

    def get_context_for_primitive(self, primitive_name: str) -> str:
        """
        Get context string tailored for a specific primitive.

        Different primitives may need different context emphasis.

        Args:
            primitive_name: Name of the primitive requesting context

        Returns:
            Context string optimized for the primitive
        """
        lines = []

        # Always include turn info
        lines.append(f"턴: {self.global_context.current_turn} ({self.global_context.game_era} 시대)")

        # Strategy summary
        strategy_str = self.high_level_context.get_strategy_string()
        lines.append(f"전략: {strategy_str}")

        # Primitive-specific context
        if primitive_name == "unit_ops_primitive":
            # Unit operations need military and unit info
            if self.global_context.units_by_type:
                lines.append(f"보유 유닛: {self.global_context.units_by_type}")
            if self.global_context.is_at_war():
                lines.append(f"⚔️ 전쟁 중: {', '.join(self.global_context.active_wars)}")
            if self.primitive_context.selected_unit_info:
                lines.append(f"선택된 유닛: {self.primitive_context.selected_unit_info}")

        elif primitive_name == "research_select_primitive":
            # Research needs science output and available techs
            lines.append(f"과학 출력: +{self.global_context.science_per_turn:.1f}/턴")
            if self.global_context.current_research:
                lines.append(
                    f"연구 중: {self.global_context.current_research} ({self.global_context.research_turns_left}턴)"
                )
            if self.global_context.available_techs:
                lines.append(f"연구 가능: {', '.join(self.global_context.available_techs[:5])}")

        elif primitive_name in ("culture_decision_primitive",):
            # Culture needs culture output and civics
            lines.append(f"문화 출력: +{self.global_context.culture_per_turn:.1f}/턴")
            if self.global_context.current_civic:
                lines.append(
                    f"사회제도: {self.global_context.current_civic} ({self.global_context.civic_turns_left}턴)"
                )
            if self.global_context.available_civics:
                lines.append(f"선택 가능: {', '.join(self.global_context.available_civics[:5])}")

        elif primitive_name == "city_production_primitive":
            # Production needs city info
            if self.global_context.cities:
                lines.append(f"도시 수: {len(self.global_context.cities)}")
                for city in self.global_context.cities[:3]:
                    if city.current_production:
                        lines.append(f"  {city.name}: {city.current_production} ({city.production_turns_left}턴)")

        elif primitive_name == "diplomatic_primitive":
            # Diplomacy needs civ relations
            if self.global_context.known_civilizations:
                lines.append("알려진 문명:")
                for civ in self.global_context.known_civilizations[:5]:
                    lines.append(f"  - {civ.name}: {civ.diplomatic_status.value}")

        elif primitive_name == "governor_primitive":
            # Governor needs city and governor info
            if self.global_context.cities:
                governed = [c for c in self.global_context.cities if c.has_governor]
                ungoverned = [c for c in self.global_context.cities if not c.has_governor]
                if governed:
                    lines.append(f"총독 배치된 도시: {', '.join(c.name for c in governed)}")
                if ungoverned:
                    lines.append(f"총독 미배치 도시: {', '.join(c.name for c in ungoverned)}")

        elif primitive_name == "policy_primitive":
            # Policy decisions - add any relevant policy context
            pass  # Currently no specific policy context in GlobalContext

        elif primitive_name == "combat_primitive":
            # Combat needs military strength and war status
            lines.append(f"군사력: {self.global_context.military_strength}")
            if self.global_context.is_at_war():
                lines.append(f"⚔️ 전쟁 상대: {', '.join(self.global_context.active_wars)}")

        elif primitive_name == "religion_primitive":
            # Religion needs faith info
            if hasattr(self.global_context, "faith_per_turn"):
                lines.append(f"신앙 출력: +{self.global_context.faith_per_turn:.1f}/턴")

        elif primitive_name == "war_primitive":
            # War needs military and diplomacy info
            lines.append(f"군사력: {self.global_context.military_strength}")
            if self.global_context.known_civilizations:
                lines.append("알려진 문명:")
                for civ in self.global_context.known_civilizations[:5]:
                    lines.append(f"  - {civ.name}: {civ.diplomatic_status.value}")

        elif primitive_name == "deal_primitive":
            # Deal needs diplomacy and resource info
            if self.global_context.known_civilizations:
                lines.append("알려진 문명:")
                for civ in self.global_context.known_civilizations[:5]:
                    lines.append(f"  - {civ.name}: {civ.diplomatic_status.value}")

        elif primitive_name == "voting_primitive":
            # World congress needs diplomacy info
            if self.global_context.known_civilizations:
                lines.append("알려진 문명:")
                for civ in self.global_context.known_civilizations[:3]:
                    lines.append(f"  - {civ.name}: {civ.diplomatic_status.value}")

        elif primitive_name == "era_primitive":
            # Era dedication needs era and score info
            lines.append(f"현재 시대: {self.global_context.game_era}")

        # Add threats and opportunities if relevant
        if self.high_level_context.active_threats:
            lines.append(f"⚠️ 위협: {', '.join(self.high_level_context.active_threats[:3])}")

        # Add recent action context (avoid repeating same actions)
        if self.primitive_context.recent_actions:
            last_actions = self.primitive_context.get_last_actions(3)
            if last_actions:
                action_strs = []
                for a in last_actions:
                    if a.action_type == "click":
                        action_strs.append(f"click({a.x},{a.y})")
                    elif a.action_type == "press":
                        action_strs.append(f"press({a.key})")
                lines.append(f"최근 액션: {', '.join(action_strs)}")

        # Add recent macro-turn summaries (last 2)
        macro_summaries = self.get_macro_turn_summaries(last_n=2)
        if macro_summaries:
            lines.append("")
            lines.append("이전 턴 요약:")
            for i, s in enumerate(macro_summaries, 1):
                lines.append(f"  [{i}] {s}")

        return "\n".join(lines) if lines else "게임 상태 정보 없음"

    def get_strategy_string(self) -> str:
        """Get the current strategy as a prompt string."""
        return self.high_level_context.get_strategy_string()

    def get_policy_tab_cache(self) -> PolicyTabCalibrationCache:
        """Return a deep copy of the session-persistent policy tab cache."""
        return copy.deepcopy(self._policy_tab_cache)

    def has_full_policy_tab_cache(self) -> bool:
        """Whether all five policy tab coordinates are confirmed for this session."""
        return self._policy_tab_cache.is_full()

    # ==================== Write Methods ====================

    def update_global_context(self, **kwargs: Any) -> None:
        """
        Update global context fields.

        Args:
            **kwargs: Fields to update on GlobalContext
        """
        for key, value in kwargs.items():
            if hasattr(self.global_context, key):
                setattr(self.global_context, key, value)
            else:
                logger.warning(f"Unknown GlobalContext field: {key}")

        self.global_context.update_timestamp()
        self._last_update = datetime.now()

    def set_strategy(self, strategy: StructuredStrategy) -> None:
        """Set the current strategy."""
        self.high_level_context.set_strategy(strategy)
        self._last_update = datetime.now()
        logger.info(f"Strategy set: {strategy.victory_goal.value} victory, phase: {strategy.current_phase}")

    def record_action(
        self,
        action_type: str,
        primitive: str,
        x: int = 0,
        y: int = 0,
        end_x: int = 0,
        end_y: int = 0,
        key: str = "",
        text: str = "",
        result: str = "success",
        error_message: str = "",
    ) -> None:
        """
        Record an executed action.

        Args:
            action_type: Type of action (click, press, drag, etc.)
            primitive: Name of the primitive that generated the action
            x, y: Normalized coordinates (if applicable)
            end_x, end_y: End coordinates for drag actions
            key: Key pressed (for press actions)
            text: Text typed (for type actions)
            result: "success" or "failed"
            error_message: Error message if failed
        """
        self.primitive_context.add_action(
            action_type=action_type,
            primitive=primitive,
            x=x,
            y=y,
            end_x=end_x,
            end_y=end_y,
            key=key,
            text=text,
            result=result,
            error_message=error_message,
        )
        self._action_count_this_turn += 1
        self._last_update = datetime.now()

    def set_current_primitive(self, primitive_name: str) -> None:
        """Set the current primitive being executed."""
        self.primitive_context.set_current_primitive(primitive_name)

    def update_selected_unit(self, unit_info: dict[str, Any]) -> None:
        """Update the currently selected unit information."""
        self.primitive_context.update_selected_unit(unit_info)

    def replace_policy_tab_cache(
        self,
        *,
        positions: dict[str, dict[str, Any]] | None = None,
        confirmed_tabs: set[str] | list[str] | None = None,
        provisional_tabs: set[str] | list[str] | None = None,
        capture_geometry: dict[str, Any] | None = None,
        calibration_complete: bool | None = None,
    ) -> None:
        """Replace the full session policy tab cache."""
        cache = PolicyTabCalibrationCache()
        for tab_name, payload in (positions or {}).items():
            if not isinstance(payload, dict):
                continue
            try:
                screen_x = int(payload.get("screen_x", 0))
                screen_y = int(payload.get("screen_y", 0))
            except (TypeError, ValueError):
                continue
            cache.positions[tab_name] = PolicyTabCalibrationEntry(
                tab_name=tab_name,
                screen_x=screen_x,
                screen_y=screen_y,
                confirmed=bool(payload.get("confirmed", False)),
                provisional=bool(payload.get("provisional", False)),
            )
        if confirmed_tabs is not None:
            cache.confirmed_tabs = {str(tab) for tab in confirmed_tabs}
        else:
            cache.confirmed_tabs = {
                tab_name for tab_name, entry in cache.positions.items() if entry.confirmed and not entry.provisional
            }
        if provisional_tabs is not None:
            cache.provisional_tabs = {str(tab) for tab in provisional_tabs}
        else:
            cache.provisional_tabs = {tab_name for tab_name, entry in cache.positions.items() if entry.provisional}
        if isinstance(capture_geometry, dict):
            try:
                cache.capture_geometry = PolicyCaptureGeometry(
                    region_w=int(capture_geometry.get("region_w", 0)),
                    region_h=int(capture_geometry.get("region_h", 0)),
                    x_offset=int(capture_geometry.get("x_offset", 0)),
                    y_offset=int(capture_geometry.get("y_offset", 0)),
                )
            except (TypeError, ValueError):
                cache.capture_geometry = None
        cache.calibration_complete = bool(calibration_complete) if calibration_complete is not None else cache.is_full()
        self._policy_tab_cache = cache
        self._last_update = datetime.now()

    def add_policy_tab_cache_failure(self, tab_name: str) -> None:
        """Record that a cached tab failed to switch cleanly."""
        self._policy_tab_cache.distinct_failures.add(tab_name)
        self._last_update = datetime.now()

    def clear_policy_tab_cache_failures(self) -> None:
        """Clear accumulated distinct tab failures."""
        self._policy_tab_cache.distinct_failures.clear()
        self._last_update = datetime.now()

    def clear_policy_tab_cache(self) -> None:
        """Clear the full session policy tab cache."""
        self._policy_tab_cache = PolicyTabCalibrationCache()
        self._last_update = datetime.now()

    def advance_turn(
        self, primitive_used: str = "", success: bool = True, notes: str = "", flush_actions: bool = False
    ) -> None:
        """
        Record turn completion and advance to next turn.

        Args:
            primitive_used: Primary primitive used this turn
            success: Whether the turn was successful
            notes: Any notes about the turn
            flush_actions: If True, also clear recent_actions (macro-turn boundary)
        """
        # Record turn history
        turn_record = TurnRecord(
            turn_number=self.global_context.current_turn,
            primitive_used=primitive_used,
            actions_taken=self._action_count_this_turn,
            success=success,
            notes=notes,
        )
        self._turn_history.append(turn_record)

        # Advance turn counter
        self.global_context.current_turn += 1
        self.global_context.update_timestamp()

        # Reset turn-specific state
        self._action_count_this_turn = 0
        self.primitive_context.reset(flush_actions=flush_actions)

        self._last_update = datetime.now()
        logger.info(f"Advanced to turn {self.global_context.current_turn}")

    def update_game_observation(
        self,
        situation_summary: str,
        threats: list[str] | None = None,
        opportunities: list[str] | None = None,
    ) -> None:
        """
        Update high-level context with background game-state observations.

        Called by ContextUpdater to inject strategic observations extracted
        from screenshots into the high-level context layer.  Keeps only the
        latest ``_MAX_OBSERVATIONS`` notes and replaces threats/opportunities
        wholesale so stale entries don't accumulate.
        """
        _MAX_OBSERVATIONS = 3

        # Append observation, cap list length
        self.high_level_context.notes.append(situation_summary)
        if len(self.high_level_context.notes) > _MAX_OBSERVATIONS:
            self.high_level_context.notes = self.high_level_context.notes[-_MAX_OBSERVATIONS:]

        # Replace threats/opportunities with the latest detected set
        if threats is not None:
            self.high_level_context.active_threats = threats
        if opportunities is not None:
            self.high_level_context.opportunities = opportunities

        self._last_update = datetime.now()
        logger.debug("Game observation updated in high-level context")

    def add_macro_turn_summary(self, summary: str) -> None:
        """Store a macro-turn LLM summary."""
        self._macro_turn_summaries.append(summary)
        self._last_update = datetime.now()

    def get_macro_turn_summaries(self, last_n: int = 3) -> list[str]:
        """Get the last N macro-turn summaries."""
        return self._macro_turn_summaries[-last_n:]

    def add_threat(self, threat: str) -> None:
        """Add an active threat."""
        self.high_level_context.add_threat(threat)

    def remove_threat(self, threat: str) -> None:
        """Remove a threat."""
        self.high_level_context.remove_threat(threat)

    def add_opportunity(self, opportunity: str) -> None:
        """Add an opportunity."""
        self.high_level_context.add_opportunity(opportunity)

    def remove_opportunity(self, opportunity: str) -> None:
        """Remove an opportunity."""
        self.high_level_context.remove_opportunity(opportunity)

    # ==================== Utility Methods ====================

    def get_turn_history(self, last_n: int | None = None) -> list[TurnRecord]:
        """Get turn history, optionally limited to last N turns."""
        if last_n is None:
            return self._turn_history
        return self._turn_history[-last_n:]

    def get_session_duration(self) -> float:
        """Get session duration in seconds."""
        return (datetime.now() - self._session_start).total_seconds()

    def to_dict(self) -> dict[str, Any]:
        """Convert all contexts to a dictionary for serialization."""
        return {
            "global": self.global_context.to_dict(),
            "high_level": self.high_level_context.to_dict(),
            "primitive": self.primitive_context.to_dict(),
            "policy_tab_cache": self._policy_tab_cache.to_dict(),
            "session_start": self._session_start.isoformat(),
            "last_update": self._last_update.isoformat(),
            "turn_history_count": len(self._turn_history),
        }

    def __repr__(self) -> str:
        has_strategy = self.high_level_context.current_strategy is not None
        return (
            f"ContextManager(turn={self.global_context.current_turn}, "
            f"era={self.global_context.game_era}, strategy={has_strategy})"
        )
