"""
High Level Context - Stores strategy and victory-related state.

This context maintains strategic information generated by the Strategy module,
including victory goals, priorities, threats, and opportunities.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from computer_use_test.agent.modules.strategy.strategy_schemas import StructuredStrategy


@dataclass
class HighLevelContext:
    """
    High-level strategic context.

    Stores information from the Strategy module that guides
    primitive-level decision making.
    """

    # Strategy
    current_strategy: "StructuredStrategy | None" = None
    strategy_updated_at: datetime | None = None

    # Victory tracking
    victory_progress: dict[str, float] = field(default_factory=dict)
    # e.g., {"science": 0.45, "culture": 0.20, "domination": 0.10}

    # Situational awareness
    active_threats: list[str] = field(default_factory=list)
    # e.g., ["Enemy army near capital", "Low gold reserves"]

    opportunities: list[str] = field(default_factory=list)
    # e.g., ["Undefended city-state nearby", "Wonder available to build"]

    # Strategic notes
    notes: list[str] = field(default_factory=list)

    def set_strategy(self, strategy: "StructuredStrategy") -> None:
        """Update the current strategy and timestamp."""
        self.current_strategy = strategy
        self.strategy_updated_at = datetime.now()

    def add_threat(self, threat: str) -> None:
        """Add a threat to the active threats list."""
        if threat not in self.active_threats:
            self.active_threats.append(threat)

    def remove_threat(self, threat: str) -> None:
        """Remove a threat from the active threats list."""
        if threat in self.active_threats:
            self.active_threats.remove(threat)

    def add_opportunity(self, opportunity: str) -> None:
        """Add an opportunity to the opportunities list."""
        if opportunity not in self.opportunities:
            self.opportunities.append(opportunity)

    def remove_opportunity(self, opportunity: str) -> None:
        """Remove an opportunity from the opportunities list."""
        if opportunity in self.opportunities:
            self.opportunities.remove(opportunity)

    def update_victory_progress(self, victory_type: str, progress: float) -> None:
        """Update progress for a specific victory type (0.0 to 1.0)."""
        self.victory_progress[victory_type] = max(0.0, min(1.0, progress))

    def to_prompt_string(self) -> str:
        """
        Convert high-level context to a string suitable for LLM prompts.

        Returns a concise summary of strategic information.
        """
        lines = ["=== 전략 컨텍스트 ==="]

        # Strategy summary
        if self.current_strategy:
            lines.append(f"목표: {self.current_strategy.victory_goal.value} 승리")
            lines.append(f"단계: {self.current_strategy.current_phase}")
            lines.append("")
            lines.append(self.current_strategy.text)
        else:
            lines.append("전략 미설정")

        # Victory progress
        if self.victory_progress:
            lines.append("")
            lines.append("📊 승리 진행도:")
            for vtype, progress in sorted(self.victory_progress.items(), key=lambda x: -x[1]):
                bar = "█" * int(progress * 10) + "░" * (10 - int(progress * 10))
                lines.append(f"  - {vtype}: [{bar}] {progress * 100:.0f}%")

        # Threats
        if self.active_threats:
            lines.append("")
            lines.append("⚠️ 위협 요소:")
            for threat in self.active_threats[:5]:
                lines.append(f"  - {threat}")

        # Opportunities
        if self.opportunities:
            lines.append("")
            lines.append("💡 기회 요소:")
            for opp in self.opportunities[:5]:
                lines.append(f"  - {opp}")

        return "\n".join(lines)

    def get_strategy_string(self) -> str:
        """Get just the strategy as a prompt string."""
        if self.current_strategy:
            return self.current_strategy.to_prompt_string()
        return "전략 미설정 - 과학 승리를 기본 목표로 함"

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            "has_strategy": self.current_strategy is not None,
            "strategy_updated_at": self.strategy_updated_at.isoformat() if self.strategy_updated_at else None,
            "victory_progress": self.victory_progress,
            "active_threats": self.active_threats,
            "opportunities": self.opportunities,
        }
